/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package belajardatabase.pelanggan;

import belajardatabase.model.KotaTableModel;
import belajardatabase.model.PelangganTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ASEP
 */
public class Entry extends javax.swing.JPanel {
    PelangganTableModel model       = null;
    KotaTableModel      kotaModel   = null;
    javax.swing.JFrame  frame       = null;
    
    /**
     * Creates new form entry
     */
    public Entry(javax.swing.JFrame frame) {
        this.frame = frame;
        
        initComponents();
        initModel();
        
        // init kota combobox
        ResultSet rs = kotaModel.sql.select.execute();
        kotaModel.save(rs);
        kotaModel.sql.getConnection().close(rs);
        for (int i = 0; i < kotaModel.getRowCount(); i++)
            kotaComboBox.addItem(kotaModel.getValueAt(i, 1).toString());
        
        // listen when mainWindow is closed
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                model.sql.closeDBConnection();
                kotaModel.sql.closeDBConnection();
            }
        });
    }
    
    public void initModel() {
        model = new PelangganTableModel();
        kotaModel = new KotaTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        noKTPField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        priaRadioButton = new javax.swing.JRadioButton();
        wanitaRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        hariField = new javax.swing.JTextField();
        bulanField = new javax.swing.JTextField();
        tahunField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pekerjaanField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        alamatField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kotaComboBox = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        teleponField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        noHPField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        simpanButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(626, 666));
        setMinimumSize(new java.awt.Dimension(626, 666));
        setPreferredSize(new java.awt.Dimension(626, 666));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Tambah Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(388, 300));
        jPanel2.setLayout(new java.awt.GridLayout(11, 2, 0, 10));

        jLabel1.setText("No. KTP");
        jPanel2.add(jLabel1);

        noKTPField.setName("no_ktp"); // NOI18N
        jPanel2.add(noKTPField);

        jLabel2.setText("Nama");
        jPanel2.add(jLabel2);

        namaField.setName("nama"); // NOI18N
        jPanel2.add(namaField);

        jLabel3.setText("Jenis Kelamin");
        jPanel2.add(jLabel3);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        priaRadioButton.setSelected(true);
        priaRadioButton.setText("L");
        priaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priaRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(priaRadioButton);

        wanitaRadioButton.setText("P");
        wanitaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wanitaRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(wanitaRadioButton);

        jPanel2.add(jPanel1);

        jLabel4.setText("Tanggal Lahir");
        jPanel2.add(jLabel4);

        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        hariField.setText("HH");
        jPanel3.add(hariField);

        bulanField.setText("MM");
        jPanel3.add(bulanField);

        tahunField.setText("TTTT");
        jPanel3.add(tahunField);

        jPanel2.add(jPanel3);

        jLabel5.setText("Pekerjaan");
        jPanel2.add(jLabel5);

        pekerjaanField.setName("pekerjaan"); // NOI18N
        jPanel2.add(pekerjaanField);

        jLabel6.setText("Alamat");
        jPanel2.add(jLabel6);

        alamatField.setName("alamat"); // NOI18N
        jPanel2.add(alamatField);

        jLabel7.setText("Kota");
        jPanel2.add(jLabel7);

        kotaComboBox.setName("kotaComboBox"); // NOI18N
        kotaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotaComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(kotaComboBox);

        jLabel8.setText("Telepon");
        jPanel2.add(jLabel8);

        teleponField.setName("telepon"); // NOI18N
        jPanel2.add(teleponField);

        jLabel9.setText("No. HP");
        jPanel2.add(jLabel9);

        noHPField.setName("no_hp"); // NOI18N
        jPanel2.add(noHPField);

        jLabel10.setText("Email");
        jPanel2.add(jLabel10);

        emailField.setName("email"); // NOI18N
        jPanel2.add(emailField);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        simpanButton.setText("SIMPAN");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });
        jPanel5.add(simpanButton);

        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel5.add(resetButton);

        jPanel2.add(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kotaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kotaComboBoxActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        int jenkel = PelangganTableModel.PEREMPUAN;
        if (priaRadioButton.isSelected()) jenkel = PelangganTableModel.PRIA;
        
        String tanggalLahir = tahunField.getText() + "-" + bulanField.getText()
                + "-" + hariField.getText();
        
        String namaKota = kotaComboBox.getSelectedItem().toString();
        int idKota = kotaModel.getIdKotaByNamaKota(namaKota);
        
        
        model.sql.insert.reset();
        model.sql.insert.value("noKTP", noKTPField.getText());
        model.sql.insert.value("nama", namaField.getText());
        model.sql.insert.value("jenisKelamin", jenkel);
        model.sql.insert.value("tanggalLahir", tanggalLahir);
        model.sql.insert.value("pekerjaan", pekerjaanField.getText());
        model.sql.insert.value("alamat", alamatField.getText());
        model.sql.insert.value("idKota", idKota);
        model.sql.insert.value("telepon", teleponField.getText());
        model.sql.insert.value("handphone", noHPField.getText());
        model.sql.insert.value("email", emailField.getText());

        boolean success = model.sql.insert.execute();
        
        String pesan = "Gagal menambah data";
        if (success) pesan = "Sukses menambah data";
        
        JOptionPane.showMessageDialog(frame, pesan);
        
        if (success) reset();
        
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void priaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priaRadioButtonActionPerformed
        wanitaRadioButton.setSelected(false);
    }//GEN-LAST:event_priaRadioButtonActionPerformed

    private void wanitaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wanitaRadioButtonActionPerformed
        priaRadioButton.setSelected(false);
    }//GEN-LAST:event_wanitaRadioButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    public void reset() {
        noKTPField.setText("");
        namaField.setText("");
        priaRadioButton.setSelected(true);
        wanitaRadioButton.setSelected(false);
        tahunField.setText("");
        bulanField.setText("");
        hariField.setText("");
        pekerjaanField.setText("");
        alamatField.setText("");
        kotaComboBox.setSelectedIndex(0);
        teleponField.setText("");
        noHPField.setText("");
        emailField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatField;
    private javax.swing.JTextField bulanField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField hariField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> kotaComboBox;
    private javax.swing.JTextField namaField;
    private javax.swing.JTextField noHPField;
    private javax.swing.JTextField noKTPField;
    private javax.swing.JTextField pekerjaanField;
    private javax.swing.JRadioButton priaRadioButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTextField tahunField;
    private javax.swing.JTextField teleponField;
    private javax.swing.JRadioButton wanitaRadioButton;
    // End of variables declaration//GEN-END:variables
}
