/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package belajardatabase.pelanggan;

import belajardatabase.mysqlop.MyDBConnection;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


/**
 *
 * @author Tio
 */
public class pelangganForm extends javax.swing.JFrame {

    /**
     * Creates new form pelangganForm
     */
    
    PreparedStatement pst = null;
    ResultSet rs = null;
    public pelangganForm() {
        mdbc = new MyDBConnection();
        mdbc.init();
        Connection conn =mdbc.getMyConnection();
        try {
           stmt = conn.createStatement();
        } catch (SQLException e) {
            System.out.println("Error inside `insertTable` : " + e.getMessage());
        }
        
        initComponents();
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        // TODO add your handling code here:
        mdbc.close(stmt);
        mdbc.destroy();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        field_no_ktp = new javax.swing.JTextField();
        field_nama = new javax.swing.JTextField();
        field_pekerjaan = new javax.swing.JTextField();
        field_alamat = new javax.swing.JTextField();
        field_telepon = new javax.swing.JTextField();
        field_no_hp = new javax.swing.JTextField();
        field_email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        radio_l = new javax.swing.JRadioButton();
        radio_p = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        field_tgl_lahir = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        sewaMenu = new javax.swing.JMenu();
        sewaTambahMenuItem = new javax.swing.JMenuItem();
        sewaListingMenuItem = new javax.swing.JMenuItem();
        mobilMenu = new javax.swing.JMenu();
        mobilTambahMenuItem = new javax.swing.JMenuItem();
        mobilListingMenuItem = new javax.swing.JMenuItem();
        keluarMenu = new javax.swing.JMenu();
        keluarKeluarMenuItem = new javax.swing.JMenuItem();
        keluarLogoutMenuItem = new javax.swing.JMenuItem();
        pelangganMenu = new javax.swing.JMenu();
        pelangganTambahMenuItem = new javax.swing.JMenuItem();
        pelangganListingMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("pelangganFrame"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Tambah Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(388, 300));

        jLabel1.setText("No. KTP");

        jLabel2.setText("Nama");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Tanggal Lahir");

        jLabel5.setText("Pekerjaan");

        jLabel6.setText("Alamat");

        jLabel7.setText("Kota");

        jLabel8.setText("Telepon");

        jLabel9.setText("No. HP");

        jLabel10.setText("Email");

        field_no_ktp.setName("no_ktp"); // NOI18N

        field_nama.setName("nama"); // NOI18N

        field_pekerjaan.setName("pekerjaan"); // NOI18N

        field_alamat.setName("alamat"); // NOI18N

        field_telepon.setName("telepon"); // NOI18N

        field_no_hp.setName("no_hp"); // NOI18N

        field_email.setName("email"); // NOI18N

        jButton1.setText("Simpan");
        jButton1.setName("btn_simpan"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.setName("btn_reset"); // NOI18N
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_l);
        radio_l.setText("L");
        radio_l.setName("rb_l"); // NOI18N
        radio_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_lActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_p);
        radio_p.setText("P");
        radio_p.setName("rb_p"); // NOI18N
        radio_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_pActionPerformed(evt);
            }
        });

        jComboBox1.setName("jComboBox1"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        field_tgl_lahir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-M-d"))));
        field_tgl_lahir.setText("2017-02-02");
        field_tgl_lahir.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field_email, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field_no_hp, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addComponent(field_pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(field_no_ktp, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field_alamat)
                            .addComponent(jComboBox1, 0, 153, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radio_l)
                                .addGap(26, 26, 26)
                                .addComponent(radio_p))
                            .addComponent(field_tgl_lahir))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(field_no_ktp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(field_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(radio_l)
                    .addComponent(radio_p))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(field_tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(field_pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(field_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(field_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(field_no_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(field_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn_reset))
                .addGap(22, 22, 22))
        );

        sewaMenu.setText("Sewa");

        sewaTambahMenuItem.setText("Tambah");
        sewaTambahMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaTambahMenuItemActionPerformed(evt);
            }
        });
        sewaMenu.add(sewaTambahMenuItem);

        sewaListingMenuItem.setText("Listing");
        sewaMenu.add(sewaListingMenuItem);

        jMenuBar1.add(sewaMenu);

        mobilMenu.setText("Mobil");

        mobilTambahMenuItem.setText("Tambah");
        mobilTambahMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilTambahMenuItemActionPerformed(evt);
            }
        });
        mobilMenu.add(mobilTambahMenuItem);

        mobilListingMenuItem.setText("Listing");
        mobilMenu.add(mobilListingMenuItem);

        jMenuBar1.add(mobilMenu);

        keluarMenu.setText("Keluar");

        keluarKeluarMenuItem.setText("Keluar");
        keluarKeluarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarKeluarMenuItemActionPerformed(evt);
            }
        });
        keluarMenu.add(keluarKeluarMenuItem);

        keluarLogoutMenuItem.setText("Logout");
        keluarMenu.add(keluarLogoutMenuItem);

        jMenuBar1.add(keluarMenu);

        pelangganMenu.setText("Pelanggan");

        pelangganTambahMenuItem.setText("Tambah");
        pelangganTambahMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganTambahMenuItemActionPerformed(evt);
            }
        });
        pelangganMenu.add(pelangganTambahMenuItem);

        pelangganListingMenuItem.setText("Listing");
        pelangganMenu.add(pelangganListingMenuItem);

        jMenuBar1.add(pelangganMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sewaTambahMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaTambahMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sewaTambahMenuItemActionPerformed

    private void mobilTambahMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilTambahMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilTambahMenuItemActionPerformed

    private void keluarKeluarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarKeluarMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarKeluarMenuItemActionPerformed

    private void pelangganTambahMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganTambahMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelangganTambahMenuItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String no_ktp = field_no_ktp.getText();
        String nama = field_nama.getText();
        String tgl_lahir = field_tgl_lahir.getText();
        String pekerjaan = field_pekerjaan.getText();
        String alamat = field_alamat.getText();
        String kota = (String) jComboBox1.getSelectedItem();
        String no_telp = field_telepon.getText();
        String email = field_email.getText();
        String no_hp = field_no_hp.getText();
        Integer JenKel;
        if (radio_l.isSelected()){
             JenKel = 0;
        }else{
             JenKel = 1;
        }
        
        mdbc = new MyDBConnection();
        mdbc.init();
        Connection conn =mdbc.getMyConnection();
        try {
            String query = "SELECT * FROM kota WHERE namaKota=" + quotate(kota);
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
            while (rs.next()) {  
                kota = rs.getString("idKota");
            }
        } catch (Exception e) {
            
        }
        String insertStr;
        
        try {
            insertStr = "INSERT INTO pelanggan (noKTP, nama, jenisKelamin, tanggalLahir, pekerjaan, alamat, idKota, telepon, handphone, email) VALUES ("
                    + quotate(no_ktp) + ","
                    + quotate(nama) + ","
                    + JenKel + ","
                    + quotate(tgl_lahir) + ","
                    + quotate(pekerjaan) + ","
                    + quotate(alamat) + ","
                    + kota + ","
                    + quotate(no_telp) + ","
                    + quotate(no_hp) + ","
                    + quotate(email)
                    + ")";
            
            int done = stmt.executeUpdate(insertStr);
            
            JOptionPane.showMessageDialog(null, "Berhasil menambahkan data");
        
            reset();
            
            initComponents();
        } catch (Exception e) {
            System.out.println("Error in `sendButtonActionPerformed` : " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void radio_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_pActionPerformed

    private void radio_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_lActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_lActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        mdbc = new MyDBConnection();
        mdbc.init();
        Connection conn =mdbc.getMyConnection();
        try {
            
            String query = "SELECT * FROM kota";
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
             
            while (rs.next()) {      
                String kota = rs.getString("namaKota");
                jComboBox1.addItem(kota);
            }
             
        } catch (SQLException e) {
            System.out.println("Error in `combobox kota` : " + e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened
    public void reset() {
        field_no_ktp.setText("");
        field_nama.setText("");
        field_tgl_lahir.setText("");
        field_pekerjaan.setText("");
        field_alamat.setText("");
        field_telepon.setText("");
        field_email.setText("");
        field_no_hp.setText("");
    }
       
    public String quotate(String content) {
        return "'" + content + "'";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelangganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelangganForm().setVisible(true);
            }
        });
    }
    
    private MyDBConnection mdbc;
    private java.sql.Statement stmt;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField field_alamat;
    private javax.swing.JTextField field_email;
    private javax.swing.JTextField field_nama;
    private javax.swing.JTextField field_no_hp;
    private javax.swing.JTextField field_no_ktp;
    private javax.swing.JTextField field_pekerjaan;
    private javax.swing.JTextField field_telepon;
    private javax.swing.JFormattedTextField field_tgl_lahir;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem keluarKeluarMenuItem;
    private javax.swing.JMenuItem keluarLogoutMenuItem;
    private javax.swing.JMenu keluarMenu;
    private javax.swing.JMenuItem mobilListingMenuItem;
    private javax.swing.JMenu mobilMenu;
    private javax.swing.JMenuItem mobilTambahMenuItem;
    private javax.swing.JMenuItem pelangganListingMenuItem;
    private javax.swing.JMenu pelangganMenu;
    private javax.swing.JMenuItem pelangganTambahMenuItem;
    private javax.swing.JRadioButton radio_l;
    private javax.swing.JRadioButton radio_p;
    private javax.swing.JMenuItem sewaListingMenuItem;
    private javax.swing.JMenu sewaMenu;
    private javax.swing.JMenuItem sewaTambahMenuItem;
    // End of variables declaration//GEN-END:variables
}
