/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package belajardatabase.pelanggan;

import belajardatabase.model.KotaTableModel;
import belajardatabase.model.MobilTableModel;
import belajardatabase.model.PelangganTableModel;
import belajardatabase.utilities.Pagination;
import belajardatabase.utilities.PaginationGUIComponent;
import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import javax.swing.table.TableColumn;

/**
 *
 * @author ASEP
 */
public class View extends javax.swing.JPanel {
    PelangganTableModel model       = null;
    Pagination          pagination  = null;

    /**
     * Creates new form view
     */
    public View(javax.swing.JFrame frame) {
        initComponents();
        initModel();
        initPagination();
        initTable();
        
        // listen when mainWindow is closed
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                model.sql.closeDBConnection();
            }
        });
    }
    
    public void initModel() {
        model = new PelangganTableModel();
        
        model.sql.select.limit(model.dataPerPage);
        model.sql.select.offset(0);
        
        ResultSet rs = model.sql.select.execute();
        model.save(rs);
        model.sql.getConnection().close(rs);
    }
    
    public void initPagination() {
        pagination = new Pagination();
        pagination.setModel(model);
        pagination.setPageLength(model.dataPerPage);
        pagination.GUIComponent.setLabel(positionPaginationLabel);
        pagination.GUIComponent.setComboBox(paginationComboBox);
        pagination.init();
    }
    
    public void initTable() {
        viewTable.setModel(model);
        
        // leave only 4 column in table
        for (int i = 4; i < model.getColumnCount(); i++) {
            TableColumn col = viewTable.getColumnModel().getColumn(4);
            viewTable.getColumnModel().removeColumn(col);
        }
        
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pencarianField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tambahButton = new javax.swing.JButton();
        viewScrollPane = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        lastPaginationButton = new javax.swing.JButton();
        nextPaginationButton = new javax.swing.JButton();
        paginationComboBox = new javax.swing.JComboBox();
        previousPaginationButton = new javax.swing.JButton();
        firstPaginationButton = new javax.swing.JButton();
        positionPaginationLabel = new javax.swing.JLabel();
        dataDetailPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        noKTPField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pekerjaanField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        alamatField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jenisKelaminField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        kotaField = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tanggalLahirField = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        teleponField = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        noHPField = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        ubahButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(626, 666));
        setMinimumSize(new java.awt.Dimension(626, 666));

        pencarianField.setToolTipText("Kotak Pencarian");
        pencarianField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5), javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 16, new javax.swing.ImageIcon("C:\\Users\\ASEP\\Downloads\\1498141047_icon-111-search.png"))))); // NOI18N
        pencarianField.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pencarianField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Pencarian :");

        tambahButton.setText("Tambah");

        viewTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        viewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTableMouseClicked(evt);
            }
        });
        viewScrollPane.setViewportView(viewTable);

        lastPaginationButton.setText(">>");
        lastPaginationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastPaginationButtonActionPerformed(evt);
            }
        });

        nextPaginationButton.setText(">");
        nextPaginationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPaginationButtonActionPerformed(evt);
            }
        });

        paginationComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paginationComboBoxItemStateChanged(evt);
            }
        });

        previousPaginationButton.setText("<");
        previousPaginationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousPaginationButtonActionPerformed(evt);
            }
        });

        firstPaginationButton.setText("<<");
        firstPaginationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPaginationButtonActionPerformed(evt);
            }
        });

        positionPaginationLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        positionPaginationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        positionPaginationLabel.setText("Halaman 1 dari 200");
        positionPaginationLabel.setAlignmentX(0.5F);

        dataDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Informasi secara Detail"));
        dataDetailPanel.setLayout(new java.awt.GridLayout(6, 2, 40, 10));

        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel8.setText("No. KTP");
        jPanel4.add(jLabel8);

        noKTPField.setEditable(false);
        noKTPField.setText("Pilih baris data");
        jPanel4.add(noKTPField);

        dataDetailPanel.add(jPanel4);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel12.setText("Pekerjaan");
        jPanel3.add(jLabel12);

        pekerjaanField.setEditable(false);
        pekerjaanField.setText("Pilih baris data");
        jPanel3.add(pekerjaanField);

        dataDetailPanel.add(jPanel3);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel10.setText("Nama");
        jPanel2.add(jLabel10);

        namaField.setEditable(false);
        namaField.setText("Pilih baris data");
        jPanel2.add(namaField);

        dataDetailPanel.add(jPanel2);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel14.setText("Alamat");
        jPanel11.add(jLabel14);

        alamatField.setEditable(false);
        alamatField.setText("Pilih baris data");
        jPanel11.add(alamatField);

        dataDetailPanel.add(jPanel11);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel18.setText("Jenis Kelamin");
        jPanel8.add(jLabel18);

        jenisKelaminField.setEditable(false);
        jenisKelaminField.setText("Pilih baris data");
        jPanel8.add(jenisKelaminField);

        dataDetailPanel.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel16.setText("Kota");
        jPanel9.add(jLabel16);

        kotaField.setEditable(false);
        kotaField.setText("Pilih baris data");
        jPanel9.add(kotaField);

        dataDetailPanel.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel19.setText("Tanggal Lahir");
        jPanel10.add(jLabel19);

        tanggalLahirField.setEditable(false);
        tanggalLahirField.setText("Pilih baris data");
        jPanel10.add(tanggalLahirField);

        dataDetailPanel.add(jPanel10);

        jPanel12.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel21.setText("Telepon");
        jPanel12.add(jLabel21);

        teleponField.setEditable(false);
        teleponField.setText("Pilih baris data");
        jPanel12.add(teleponField);

        dataDetailPanel.add(jPanel12);

        jPanel14.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel20.setText("No. HP");
        jPanel14.add(jLabel20);

        noHPField.setEditable(false);
        noHPField.setText("Pilih baris data");
        jPanel14.add(noHPField);

        dataDetailPanel.add(jPanel14);

        jPanel15.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel22.setText("Email");
        jPanel15.add(jLabel22);

        emailField.setEditable(false);
        emailField.setText("Pilih baris data");
        jPanel15.add(emailField);

        dataDetailPanel.add(jPanel15);

        jPanel13.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        ubahButton.setText("Ubah");
        ubahButton.setEnabled(false);
        jPanel13.add(ubahButton);

        hapusButton.setText("Hapus");
        hapusButton.setEnabled(false);
        jPanel13.add(hapusButton);

        dataDetailPanel.add(jPanel13);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pencarianField, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstPaginationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previousPaginationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paginationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextPaginationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastPaginationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(positionPaginationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dataDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(pencarianField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousPaginationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstPaginationButton)
                    .addComponent(paginationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextPaginationButton)
                    .addComponent(lastPaginationButton)
                    .addComponent(positionPaginationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pencarianFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianFieldActionPerformed
        String searchText = pencarianField.getText();

        // reset where clause
        String sign = "USER SEARCH";
        model.sql.select.removeWhereBySegmentSign(sign);

        model.sql.select.whereSegmentStart(sign);
        model.sql.select.where("noKTP", "LIKE", "%" + searchText + "%");
        model.sql.select.orWhere("nama", "LIKE", "%" + searchText + "%");
        model.sql.select.orWhere("alamat", "LIKE", "%" + searchText + "%");
        model.sql.select.orWhere("telepon", "LIKE", "%" + searchText + "%");
        model.sql.select.orWhere("handphone", "LIKE", "%" + searchText + "%");
        model.sql.select.orWhere("email", "LIKE", "%" + searchText + "%");
        model.sql.select.whereSegmentEnd(sign);

        int newOffset = pagination.isSQLChanged.updatePagination();
        pagination.isSQLChanged.GUIComponent.reinitComboBox();
        pagination.GUIComponent.update();

        model.sql.select.offset(newOffset);
        ResultSet rs = model.sql.select.execute();
        model.save(rs);
        model.sql.getConnection().close(rs);

        updateTable();
    }//GEN-LAST:event_pencarianFieldActionPerformed

    private void viewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTableMouseClicked
        int row = viewTable.getSelectedRow();

        if (row != -1) {
            String noKTP = model.getValueAt(row, 0).toString();
            String nama = model.getValueAt(row, 1).toString();
            String tanggalLahir = model.getValueAt(row, 2).toString();
            String pekerjaan = model.getValueAt(row, 3).toString();
            String alamat = model.getValueAt(row, 4).toString();
            String jenisKelamin = model.getValueAt(row, 5).toString();
            
            
            
            String idKota = model.getValueAt(row, 6).toString();
            String telepon = model.getValueAt(row, 7).toString();
            String handphone = model.getValueAt(row, 8).toString();
            String email = model.getValueAt(row, 9).toString();
            
            int jenkel = Integer.valueOf(jenisKelamin);
            KotaTableModel kotaModel = new KotaTableModel();
            String namaKota = kotaModel.getNamaKotaById(
                    Integer.valueOf(idKota)
            );
            
            noKTPField.setText(noKTP);
            namaField.setText(nama);
            if (jenkel == PelangganTableModel.PRIA) {
                jenisKelaminField.setText("Laki-laki");
            } else {
                jenisKelaminField.setText("Perempuan");
            }
            tanggalLahirField.setText(tanggalLahir);
            pekerjaanField.setText(pekerjaan);
            alamatField.setText(alamat);
            kotaField.setText(namaKota);
            teleponField.setText(telepon);
            noHPField.setText(handphone);
            emailField.setText(email);

            ubahButton.setEnabled(true);
            hapusButton.setEnabled(true);
        }
    }//GEN-LAST:event_viewTableMouseClicked

    private void lastPaginationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastPaginationButtonActionPerformed
        int newOffset = pagination.jumpToLast();
        pagination.GUIComponent.update();

        model.sql.select.offset(newOffset);
        ResultSet rs = model.sql.select.execute();
        model.save(rs);
        model.sql.getConnection().close(rs);

        updateTable();
    }//GEN-LAST:event_lastPaginationButtonActionPerformed

    private void nextPaginationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPaginationButtonActionPerformed
        int newOffset = pagination.moveNext();
        pagination.GUIComponent.update();

        model.sql.select.offset(newOffset);
        ResultSet rs = model.sql.select.execute();
        model.save(rs);
        model.sql.getConnection().close(rs);

        updateTable();
    }//GEN-LAST:event_nextPaginationButtonActionPerformed

    private void paginationComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paginationComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.DESELECTED &&
            pagination.GUIComponent.getComboBoxStatus() ==
            PaginationGUIComponent.COMBOBOX_ACCEPT_ANY_ACTION)
        {
            System.out.println("Posisi " + "paginationComboBox");

            int selectedPage = Integer.valueOf(paginationComboBox
                .getSelectedItem()
                .toString());

            int newOffset = pagination.jumpTo(selectedPage);
            pagination.GUIComponent.update();

            model.sql.select.offset(newOffset);
            ResultSet rs = model.sql.select.execute();
            model.save(rs);
            model.sql.getConnection().close(rs);

            updateTable();

            resetDataDetail();
        }
    }//GEN-LAST:event_paginationComboBoxItemStateChanged

    private void previousPaginationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousPaginationButtonActionPerformed
        int newOffset = pagination.movePrevious();
        pagination.GUIComponent.update();

        model.sql.select.offset(newOffset);
        ResultSet rs = model.sql.select.execute();
        model.save(rs);
        model.sql.getConnection().close(rs);

        updateTable();
    }//GEN-LAST:event_previousPaginationButtonActionPerformed

    private void firstPaginationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPaginationButtonActionPerformed
        int newOffset = pagination.jumpToFirst();
        pagination.GUIComponent.update();

        model.sql.select.offset(newOffset);
        ResultSet rs = model.sql.select.execute();
        model.save(rs);
        model.sql.getConnection().close(rs);

        updateTable();
    }//GEN-LAST:event_firstPaginationButtonActionPerformed

    public void updateTable() {
        model.fireTableDataChanged();
    }
    
    public void resetDataDetail() {
        noKTPField.setText("Pilih baris data");
        namaField.setText("Pilih baris data");
        jenisKelaminField.setText("Pilih baris data");
        tanggalLahirField.setText("Pilih baris data");
        pekerjaanField.setText("Pilih baris data");
        alamatField.setText("Pilih baris data");
        kotaField.setText("Pilih baris data");
        teleponField.setText("Pilih baris data");
        noHPField.setText("Pilih baris data");
        emailField.setText("Pilih baris data");
        ubahButton.setEnabled(false);
        hapusButton.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatField;
    private javax.swing.JPanel dataDetailPanel;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton firstPaginationButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jenisKelaminField;
    private javax.swing.JTextField kotaField;
    private javax.swing.JButton lastPaginationButton;
    private javax.swing.JTextField namaField;
    private javax.swing.JButton nextPaginationButton;
    private javax.swing.JTextField noHPField;
    private javax.swing.JTextField noKTPField;
    private javax.swing.JComboBox paginationComboBox;
    private javax.swing.JTextField pekerjaanField;
    private javax.swing.JTextField pencarianField;
    private javax.swing.JLabel positionPaginationLabel;
    private javax.swing.JButton previousPaginationButton;
    private javax.swing.JButton tambahButton;
    private javax.swing.JTextField tanggalLahirField;
    private javax.swing.JTextField teleponField;
    private javax.swing.JButton ubahButton;
    private javax.swing.JScrollPane viewScrollPane;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
