/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package belajardatabase.penyewaan;

import belajardatabase.model.KotaTableModel;
import belajardatabase.model.MobilTableModel;
import belajardatabase.model.PelangganTableModel;
import belajardatabase.model.PenyewaanTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ASEP
 */
public class Entry extends javax.swing.JPanel {
    MobilTableModel mobilModel = null;
    PelangganTableModel pelangganModel = null;
    PenyewaanTableModel penyewaanModel = null;
    
    javax.swing.JFrame frame = null;
    
    /**
     * Creates new form entry
     */
    public Entry(javax.swing.JFrame frame) {
        this.frame = frame;
        
        initComponents();
        initModel();
        
        // listen when mainWindow is closed
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                penyewaanModel.sql.closeDBConnection();
                mobilModel.sql.closeDBConnection();
                pelangganModel.sql.closeDBConnection();
            }
        });
    }
    
    public void initModel() {
        mobilModel = new MobilTableModel();
        pelangganModel = new PelangganTableModel();
        penyewaanModel = new PenyewaanTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        simpanButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        dataDetailPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        noPolisiField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        hargaSewa24JamField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        merkField = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        hargaSewa12JamField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        warnaField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        dendaPerJamField = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tahunField = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        dataDetailPanel2 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        noKTPField = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        pekerjaanField = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        alamatField = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jenisKelaminField = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        kotaField = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        tanggalLahirField = new javax.swing.JTextField();
        jPanel30 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        teleponField = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        noHPField = new javax.swing.JTextField();
        jPanel32 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        pencarianMobilField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pencarianPelangganField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tglSewaHariField = new javax.swing.JTextField();
        tglSewaBulanField = new javax.swing.JTextField();
        tglSewaTahunField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tglBatasKembaliHariField = new javax.swing.JTextField();
        tglBatasKembaliBulanField = new javax.swing.JTextField();
        tglBatasKembaliTahunField = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(626, 666));
        setMinimumSize(new java.awt.Dimension(626, 666));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Penyewaan Mobil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(388, 300));

        simpanButton.setText("SEWAKAN");
        simpanButton.setName("btn_simpan"); // NOI18N
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        resetButton.setText("RESET");
        resetButton.setName("resetButton"); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        dataDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Mobil"));
        dataDetailPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dataDetailPanel.setMinimumSize(new java.awt.Dimension(367, 163));
        dataDetailPanel.setLayout(new java.awt.GridLayout(4, 4, 30, 10));

        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel8.setText("No. Polisi");
        jPanel4.add(jLabel8);

        noPolisiField.setEditable(false);
        noPolisiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noPolisiFieldActionPerformed(evt);
            }
        });
        jPanel4.add(noPolisiField);

        dataDetailPanel.add(jPanel4);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel9.setText("Harga Sewa 24 Jam");
        jPanel3.add(jLabel9);

        hargaSewa24JamField.setEditable(false);
        jPanel3.add(hargaSewa24JamField);

        dataDetailPanel.add(jPanel3);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel10.setText("Merk");
        jPanel5.add(jLabel10);

        merkField.setEditable(false);
        merkField.setToolTipText("");
        jPanel5.add(merkField);

        dataDetailPanel.add(jPanel5);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel16.setText("Harga Sewa 12 Jam");
        jPanel11.add(jLabel16);

        hargaSewa12JamField.setEditable(false);
        jPanel11.add(hargaSewa12JamField);

        dataDetailPanel.add(jPanel11);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel12.setText("Warna");
        jPanel8.add(jLabel12);

        warnaField.setEditable(false);
        jPanel8.add(warnaField);

        dataDetailPanel.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel11.setText("Denda Per Jam ");
        jPanel9.add(jLabel11);

        dendaPerJamField.setEditable(false);
        jPanel9.add(dendaPerJamField);

        dataDetailPanel.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel14.setText("Tahun");
        jPanel10.add(jLabel14);

        tahunField.setEditable(false);
        jPanel10.add(tahunField);

        dataDetailPanel.add(jPanel10);

        jPanel12.setLayout(new java.awt.GridLayout(1, 2, 10, 0));
        dataDetailPanel.add(jPanel12);

        dataDetailPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Informasi"));
        dataDetailPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dataDetailPanel2.setMinimumSize(new java.awt.Dimension(367, 163));
        dataDetailPanel2.setLayout(new java.awt.GridLayout(5, 5, 30, 10));

        jPanel23.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel22.setText("No. KTP");
        jPanel23.add(jLabel22);

        noKTPField.setEditable(false);
        noKTPField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noKTPFieldActionPerformed(evt);
            }
        });
        jPanel23.add(noKTPField);

        dataDetailPanel2.add(jPanel23);

        jPanel24.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel23.setText("Pekerjaan");
        jPanel24.add(jLabel23);

        pekerjaanField.setEditable(false);
        jPanel24.add(pekerjaanField);

        dataDetailPanel2.add(jPanel24);

        jPanel25.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel24.setText("Nama");
        jPanel25.add(jLabel24);

        namaField.setEditable(false);
        jPanel25.add(namaField);

        dataDetailPanel2.add(jPanel25);

        jPanel26.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel25.setText("Alamat");
        jPanel26.add(jLabel25);

        alamatField.setEditable(false);
        jPanel26.add(alamatField);

        dataDetailPanel2.add(jPanel26);

        jPanel27.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel26.setText("Jenis Kelamin");
        jPanel27.add(jLabel26);

        jenisKelaminField.setEditable(false);
        jPanel27.add(jenisKelaminField);

        dataDetailPanel2.add(jPanel27);

        jPanel28.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel13.setText("Kota");
        jPanel28.add(jLabel13);

        kotaField.setEditable(false);
        jPanel28.add(kotaField);

        dataDetailPanel2.add(jPanel28);

        jPanel29.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel27.setText("Tanggal Lahir");
        jPanel29.add(jLabel27);

        tanggalLahirField.setEditable(false);
        jPanel29.add(tanggalLahirField);

        dataDetailPanel2.add(jPanel29);

        jPanel30.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel15.setText("Telepon");
        jPanel30.add(jLabel15);

        teleponField.setEditable(false);
        jPanel30.add(teleponField);

        dataDetailPanel2.add(jPanel30);

        jPanel31.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel28.setText("No. HP");
        jPanel31.add(jLabel28);

        noHPField.setEditable(false);
        jPanel31.add(noHPField);

        dataDetailPanel2.add(jPanel31);

        jPanel32.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel17.setText("Email");
        jPanel32.add(jLabel17);

        emailField.setEditable(false);
        jPanel32.add(emailField);

        dataDetailPanel2.add(jPanel32);

        pencarianMobilField.setText("No. Polisi atau Merk");
        pencarianMobilField.setToolTipText("Kotak Pencarian");
        pencarianMobilField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5), javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 16, new javax.swing.ImageIcon("C:\\Users\\ASEP\\Downloads\\1498141047_icon-111-search.png"))))); // NOI18N
        pencarianMobilField.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pencarianMobilField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianMobilFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Cari Mobil");

        pencarianPelangganField.setText("No KTP atau Nama");
        pencarianPelangganField.setToolTipText("Kotak Pencarian");
        pencarianPelangganField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5), javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 16, new javax.swing.ImageIcon("C:\\Users\\ASEP\\Downloads\\1498141047_icon-111-search.png"))))); // NOI18N
        pencarianPelangganField.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pencarianPelangganField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianPelangganFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Cari Pelanggan");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Penyewaan"));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jLabel3.setText("Tanggal Sewa");
        jPanel1.add(jLabel3);

        jPanel6.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        tglSewaHariField.setText("HH");
        jPanel6.add(tglSewaHariField);

        tglSewaBulanField.setText("MM");
        jPanel6.add(tglSewaBulanField);

        tglSewaTahunField.setText("YYYY");
        jPanel6.add(tglSewaTahunField);

        jPanel1.add(jPanel6);

        jLabel2.setText("Akhir Sewa");
        jPanel1.add(jLabel2);

        jPanel7.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        tglBatasKembaliHariField.setText("HH");
        jPanel7.add(tglBatasKembaliHariField);

        tglBatasKembaliBulanField.setText("MM");
        jPanel7.add(tglBatasKembaliBulanField);

        tglBatasKembaliTahunField.setText("YYYY");
        jPanel7.add(tglBatasKembaliTahunField);

        jPanel1.add(jPanel7);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dataDetailPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dataDetailPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41)
                                .addComponent(pencarianMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pencarianPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pencarianMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addComponent(dataDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pencarianPelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dataDetailPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pencarianMobilFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianMobilFieldActionPerformed
        String searchText = pencarianMobilField.getText();

        // reset where clause
        String sign = "USER SEARCH";
        mobilModel.sql.select.removeWhereBySegmentSign(sign);

        mobilModel.sql.select.whereSegmentStart(sign);
        mobilModel.sql.select.whereGroupingStart("");
        mobilModel.sql.select.where("noPolisi", "LIKE", "%" + searchText + "%");
        mobilModel.sql.select.orWhere("merk", "LIKE", "%" + searchText + "%");
        mobilModel.sql.select.whereGroupingEnd();
        mobilModel.sql.select.andWhere("status", "=", MobilTableModel.STATUS_TERSEDIA);
        mobilModel.sql.select.whereSegmentEnd(sign);

        ResultSet rs = mobilModel.sql.select.execute();
        mobilModel.save(rs);
        mobilModel.sql.getConnection().close(rs);
        
        if (mobilModel.getRowCount() == 1) {
            String noPolisi = mobilModel.getValueAt(0, 0).toString();
            String merk = mobilModel.getValueAt(0, 1).toString();
            String warna = mobilModel.getValueAt(0, 4).toString();
            String tahun = mobilModel.getValueAt(0, 5).toString();
            String hargaSewa12Jam = mobilModel.getValueAt(0, 2).toString();
            String hargaSewa24Jam = mobilModel.getValueAt(0, 3).toString();
            String dendaPerJam = mobilModel.getValueAt(0, 6).toString();
            String status = mobilModel.getValueAt(0, 7).toString();

            noPolisiField.setText(noPolisi);
            merkField.setText(merk);
            warnaField.setText(warna);
            tahunField.setText(tahun);
            hargaSewa12JamField.setText(hargaSewa12Jam);
            hargaSewa24JamField.setText(hargaSewa24Jam);
            dendaPerJamField.setText(dendaPerJam);
        } else {
            if (mobilModel.getRowCount() > 1) {
                JOptionPane.showMessageDialog(
                        frame,
                        "Kata kunci Anda kurang spesifik\n"
                        + "Ia cocok terhadap satu lebih data"
                );
            }
        }
    }//GEN-LAST:event_pencarianMobilFieldActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        //waktu
        String tglSewa = tglSewaTahunField.getText()
                + "-" + tglSewaBulanField.getText()
                + "-" + tglSewaHariField.getText();
        String tglBatasSewa = tglBatasKembaliTahunField.getText()
                + "-" + tglBatasKembaliBulanField.getText()
                + "-" + tglBatasKembaliHariField.getText();

        //pelanggan
        String noKTP = noKTPField.getText();

        //mobil
        String noPolisi = noPolisiField.getText();
        
        try {
            

            penyewaanModel.sql.insert.reset();
            penyewaanModel.sql.insert.value("noKTP", noKTP);
            penyewaanModel.sql.insert.value("noPolisi", noPolisi);
            penyewaanModel.sql.insert.value("tanggalSewa", tglSewa);
            penyewaanModel.sql.insert.value("batasKembali", tglBatasSewa);
            penyewaanModel.sql.insert.value("tanggalKembali", "0000-00-00");
            penyewaanModel.sql.insert.value("subTotal", 0); // nnti ketika mobil dikembalikkan
            penyewaanModel.sql.insert.value("denda", 0);
            
            mobilModel.sql.update.where("noPolisi", noPolisi);
            mobilModel.sql.update.set("status", MobilTableModel.STATUS_TIDAK_TERSEDIA);
            boolean success2 = mobilModel.sql.update.execute();
            
            boolean success1 = penyewaanModel.sql.insert.execute();
            
            String pesan = "Gagal menyewa mobil";
            if (success1 && success2) pesan = "Berhasil menyewa mobil";
            
            JOptionPane.showMessageDialog(null, pesan);

            reset();

        } catch (Exception e) {
            System.out.println("Error in `sendButtonActionPerformed` : " + e.getMessage());
        }
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void noPolisiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noPolisiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noPolisiFieldActionPerformed

    private void noKTPFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noKTPFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noKTPFieldActionPerformed

    private void pencarianPelangganFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianPelangganFieldActionPerformed
        String searchText = pencarianPelangganField.getText();

        // reset where clause
        String sign = "USER SEARCH";
        pelangganModel.sql.select.removeWhereBySegmentSign(sign);

        pelangganModel.sql.select.whereSegmentStart(sign);
        pelangganModel.sql.select.where("noKTP", "LIKE", "%" + searchText + "%");
        pelangganModel.sql.select.orWhere("nama", "LIKE", "%" + searchText + "%");
        pelangganModel.sql.select.whereSegmentEnd(sign);

        ResultSet rs = pelangganModel.sql.select.execute();
        pelangganModel.save(rs);
        pelangganModel.sql.getConnection().close(rs);
        
        if (pelangganModel.getRowCount() == 1) {
            String noKTP = pelangganModel.getValueAt(0, 0).toString();
            String nama = pelangganModel.getValueAt(0, 1).toString();
            String tanggalLahir = pelangganModel.getValueAt(0, 2).toString();
            String pekerjaan = pelangganModel.getValueAt(0, 3).toString();
            String alamat = pelangganModel.getValueAt(0, 4).toString();
            String jenisKelamin = pelangganModel.getValueAt(0, 5).toString();
            String idKota = pelangganModel.getValueAt(0, 6).toString();
            String telepon = pelangganModel.getValueAt(0, 7).toString();
            String handphone = pelangganModel.getValueAt(0, 8).toString();
            String email = pelangganModel.getValueAt(0, 9).toString();
            
            if (isCanRentACar(noKTP) == false) return;

            int jenkel = Integer.valueOf(jenisKelamin);
            KotaTableModel kotaModel = new KotaTableModel();
            String namaKota = kotaModel.getNamaKotaById(
                    Integer.valueOf(idKota)
            );

            noKTPField.setText(noKTP);
            namaField.setText(nama);
            if (jenkel == PelangganTableModel.PRIA) {
                jenisKelaminField.setText("Laki-laki");
            } else {
                jenisKelaminField.setText("Perempuan");
            }
            tanggalLahirField.setText(tanggalLahir);
            pekerjaanField.setText(pekerjaan);
            alamatField.setText(alamat);
            kotaField.setText(namaKota);
            teleponField.setText(telepon);
            noHPField.setText(handphone);
            emailField.setText(email);
        } else {
            if (pelangganModel.getRowCount() > 1) {
                JOptionPane.showMessageDialog(
                        frame,
                        "Kata kunci Anda kurang spesifik\n"
                        + "Ia cocok terhadap satu lebih data"
                );
            }
        }
    }//GEN-LAST:event_pencarianPelangganFieldActionPerformed

    // pelanggan yang bisa menyewa adalah yang sedang tidak menyewa sebuah
    // kendaraan. Dengan kata lain, penyewa tersebut tidak boleh menyewa 2 kali
    public boolean isCanRentACar(String noKTP) {
        penyewaanModel.sql.select.reset();
        penyewaanModel.sql.select.where("noKTP", "=", noKTP);
        penyewaanModel.sql.select.andWhere("tanggalKembali", "=", "0000-00-00");
        ResultSet rs = penyewaanModel.sql.select.execute();
        try {
            if (rs.next()) {
                JOptionPane.showMessageDialog(
                        frame,
                        "Pelanggan saat ini sedang menyewa",
                        "Peringatan",
                        JOptionPane.WARNING_MESSAGE
                );
                return false;
            }
        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
            return false;
        }
        penyewaanModel.sql.getConnection().close(rs);
        
        return true;
    }
    
    public void reset() {
        pencarianMobilField.setText("");
        pencarianPelangganField.setText("");
        
        noPolisiField.setText("");
        merkField.setText("");
        warnaField.setText("");
        tahunField.setText("");
        hargaSewa12JamField.setText("");
        hargaSewa24JamField.setText("");
        dendaPerJamField.setText("");
        
        noKTPField.setText("");
        namaField.setText("");
        jenisKelaminField.setText("");
        tanggalLahirField.setText("");
        pekerjaanField.setText("");
        alamatField.setText("");
        kotaField.setText("");
        teleponField.setText("");
        noHPField.setText("");
        emailField.setText("");
        
        tglSewaTahunField.setText("");
        tglSewaBulanField.setText("");
        tglSewaHariField.setText("");
        tglBatasKembaliTahunField.setText("");
        tglBatasKembaliBulanField.setText("");
        tglBatasKembaliHariField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatField;
    private javax.swing.JPanel dataDetailPanel;
    private javax.swing.JPanel dataDetailPanel2;
    private javax.swing.JTextField dendaPerJamField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField hargaSewa12JamField;
    private javax.swing.JTextField hargaSewa24JamField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jenisKelaminField;
    private javax.swing.JTextField kotaField;
    private javax.swing.JTextField merkField;
    private javax.swing.JTextField namaField;
    private javax.swing.JTextField noHPField;
    private javax.swing.JTextField noKTPField;
    private javax.swing.JTextField noPolisiField;
    private javax.swing.JTextField pekerjaanField;
    private javax.swing.JTextField pencarianMobilField;
    private javax.swing.JTextField pencarianPelangganField;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTextField tahunField;
    private javax.swing.JTextField tanggalLahirField;
    private javax.swing.JTextField teleponField;
    private javax.swing.JTextField tglBatasKembaliBulanField;
    private javax.swing.JTextField tglBatasKembaliHariField;
    private javax.swing.JTextField tglBatasKembaliTahunField;
    private javax.swing.JTextField tglSewaBulanField;
    private javax.swing.JTextField tglSewaHariField;
    private javax.swing.JTextField tglSewaTahunField;
    private javax.swing.JTextField warnaField;
    // End of variables declaration//GEN-END:variables
}
