/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package belajardatabase.penyewaan;;

import belajardatabase.model.MobilTableModel;
import belajardatabase.mysqlop.MyDBConnection;
import belajardatabase.model.PenyewaanTableModel;
import belajardatabase.utilities.PaginationPenyewaan;
import belajardatabase.utilities.PaginationPenyewaanGUIComponent;
import java.awt.event.ItemEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author Tio
 */
public class penyewaanTable extends javax.swing.JFrame {
    PenyewaanTableModel model = null;
    PaginationPenyewaan      pagination = null;

    /** Creates new form pelangganTable */
    public penyewaanTable() {
        initComponents();
        initModel();
        initPagination();
        initTable();
    }
    
    public void initModel() {
        model = new PenyewaanTableModel();
        
        String sign = "USER OPTION";
        
        model.sql.select.limit(model.dataPerPage);
        model.sql.select.offset(0);
        
        ResultSet rs = model.sql.select.execute();
        model.save(rs);
    }
    
    public void initPagination() {
        pagination = new PaginationPenyewaan();
        pagination.setModel(model);
        pagination.setPageLength(model.dataPerPage);
        pagination.GUIComponent.setLabel(positionPaginationLabel);
        pagination.GUIComponent.setComboBox(paginationComboBox);
        pagination.init();
    }
    
     
    public void initTable() {
        viewTable.setModel(model);
        
        // leave only 4 column in table
        for (int i = 4; i < 4; i++) {
            TableColumn col = viewTable.getColumnModel().getColumn(4);
            viewTable.getColumnModel().removeColumn(col);
        }
        
        updateTable();
    }
          
    private String getPencarianSQLQuery() {
        String cari = pencarianField.getText();
        return "(" +
                    "idSewa like " + quotateWithPercent(cari) + " OR " +
                    "noKTP     like " + quotateWithPercent(cari) +
                ")";
    }
    
    
    public String quotateWithPercent(String content) {
        return "'%" + content + "%'";
    }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paginationComboBoxStatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        firstPaginationButton = new javax.swing.JButton();
        previousPaginationButton = new javax.swing.JButton();
        paginationComboBox = new javax.swing.JComboBox();
        nextPaginationButton = new javax.swing.JButton();
        lastPaginationButton = new javax.swing.JButton();
        positionPaginationLabel = new javax.swing.JLabel();
        viewScrollPane = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        dataDetailPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        field_no_ktp = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        field_pekerjaan = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        field_nama = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        field_alamat = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        field_jk = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        field_kota = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        field_tgl_lahir = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        field_telepon = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        field_no_hp = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        field_email = new javax.swing.JTextField();
        dataDetailPanel2 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        noPolisiField = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        hargaSewa12JamField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        merkField = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        hargaSewa24JamField = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        warnaField = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        dendaPerJamField = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        tahunField = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        statusField = new javax.swing.JTextField();
        jPanel30 = new javax.swing.JPanel();
        pencarianField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        paginationComboBoxStatus.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(630, 800));
        setSize(new java.awt.Dimension(626, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tabel Penyewaan");

        firstPaginationButton.setText("<<");
        firstPaginationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPaginationButtonActionPerformed(evt);
            }
        });

        previousPaginationButton.setText("<");
        previousPaginationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousPaginationButtonActionPerformed(evt);
            }
        });

        paginationComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paginationComboBoxItemStateChanged(evt);
            }
        });
        paginationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginationComboBoxActionPerformed(evt);
            }
        });

        nextPaginationButton.setText(">");
        nextPaginationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPaginationButtonActionPerformed(evt);
            }
        });

        lastPaginationButton.setText(">>");
        lastPaginationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastPaginationButtonActionPerformed(evt);
            }
        });

        positionPaginationLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        positionPaginationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        positionPaginationLabel.setText("Halaman 1 dari 200");
        positionPaginationLabel.setAlignmentX(0.5F);

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        viewTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        viewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTableMouseClicked(evt);
            }
        });
        viewScrollPane.setViewportView(viewTable);

        dataDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Pelanggan"));
        dataDetailPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dataDetailPanel.setMinimumSize(new java.awt.Dimension(367, 163));
        dataDetailPanel.setLayout(new java.awt.GridLayout(5, 5, 30, 10));

        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel8.setText("No. KTP");
        jPanel4.add(jLabel8);

        field_no_ktp.setEditable(false);
        field_no_ktp.setText("Pilih baris data");
        field_no_ktp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_no_ktpActionPerformed(evt);
            }
        });
        jPanel4.add(field_no_ktp);

        dataDetailPanel.add(jPanel4);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel9.setText("Pekerjaan");
        jPanel3.add(jLabel9);

        field_pekerjaan.setEditable(false);
        field_pekerjaan.setText("Pilih baris data");
        jPanel3.add(field_pekerjaan);

        dataDetailPanel.add(jPanel3);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel10.setText("Nama");
        jPanel5.add(jLabel10);

        field_nama.setEditable(false);
        field_nama.setText("Pilih baris data");
        jPanel5.add(field_nama);

        dataDetailPanel.add(jPanel5);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel11.setText("Alamat");
        jPanel11.add(jLabel11);

        field_alamat.setEditable(false);
        field_alamat.setText("Pilih baris data");
        jPanel11.add(field_alamat);

        dataDetailPanel.add(jPanel11);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel12.setText("Jenis Kelamin");
        jPanel8.add(jLabel12);

        field_jk.setEditable(false);
        field_jk.setText("Pilih baris data");
        jPanel8.add(field_jk);

        dataDetailPanel.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel13.setText("Kota");
        jPanel9.add(jLabel13);

        field_kota.setEditable(false);
        field_kota.setText("Pilih baris data");
        jPanel9.add(field_kota);

        dataDetailPanel.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel14.setText("Tanggal Lahir");
        jPanel10.add(jLabel14);

        field_tgl_lahir.setEditable(false);
        field_tgl_lahir.setText("Pilih baris data");
        jPanel10.add(field_tgl_lahir);

        dataDetailPanel.add(jPanel10);

        jPanel12.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel15.setText("Telepon");
        jPanel12.add(jLabel15);

        field_telepon.setEditable(false);
        field_telepon.setText("Pilih baris data");
        jPanel12.add(field_telepon);

        dataDetailPanel.add(jPanel12);

        jPanel13.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel16.setText("No. HP");
        jPanel13.add(jLabel16);

        field_no_hp.setEditable(false);
        field_no_hp.setText("Pilih baris data");
        jPanel13.add(field_no_hp);

        dataDetailPanel.add(jPanel13);

        jPanel14.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel17.setText("Email");
        jPanel14.add(jLabel17);

        field_email.setEditable(false);
        field_email.setText("Pilih baris data");
        jPanel14.add(field_email);

        dataDetailPanel.add(jPanel14);

        dataDetailPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Penyewaan"));
        dataDetailPanel2.setLayout(new java.awt.GridLayout(5, 2, 40, 10));

        jPanel23.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel28.setText("No. Polisi");
        jPanel23.add(jLabel28);

        noPolisiField.setEditable(false);
        noPolisiField.setText("Pilih baris data");
        jPanel23.add(noPolisiField);

        dataDetailPanel2.add(jPanel23);

        jPanel24.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel29.setText("Harga Sewa 12 Jam");
        jPanel24.add(jLabel29);

        hargaSewa12JamField.setEditable(false);
        hargaSewa12JamField.setText("Pilih baris data");
        jPanel24.add(hargaSewa12JamField);

        dataDetailPanel2.add(jPanel24);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel30.setText("Merk");
        jPanel2.add(jLabel30);

        merkField.setEditable(false);
        merkField.setText("Pilih baris data");
        jPanel2.add(merkField);

        dataDetailPanel2.add(jPanel2);

        jPanel25.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel31.setText("Harga Sewa 24 Jam");
        jPanel25.add(jLabel31);

        hargaSewa24JamField.setEditable(false);
        hargaSewa24JamField.setText("Pilih baris data");
        jPanel25.add(hargaSewa24JamField);

        dataDetailPanel2.add(jPanel25);

        jPanel26.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel32.setText("Warna");
        jPanel26.add(jLabel32);

        warnaField.setEditable(false);
        warnaField.setText("Pilih baris data");
        jPanel26.add(warnaField);

        dataDetailPanel2.add(jPanel26);

        jPanel27.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel33.setText("Denda per Jam");
        jPanel27.add(jLabel33);

        dendaPerJamField.setEditable(false);
        dendaPerJamField.setText("Pilih baris data");
        jPanel27.add(dendaPerJamField);

        dataDetailPanel2.add(jPanel27);

        jPanel28.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel34.setText("Tahun");
        jPanel28.add(jLabel34);

        tahunField.setEditable(false);
        tahunField.setText("Pilih baris data");
        jPanel28.add(tahunField);

        dataDetailPanel2.add(jPanel28);

        jPanel29.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel35.setText("Status");
        jPanel29.add(jLabel35);

        statusField.setEditable(false);
        statusField.setText("Pilih baris data");
        jPanel29.add(statusField);

        dataDetailPanel2.add(jPanel29);

        jPanel30.setLayout(new java.awt.GridLayout(1, 2, 10, 0));
        dataDetailPanel2.add(jPanel30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(firstPaginationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previousPaginationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paginationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextPaginationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastPaginationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(positionPaginationLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewScrollPane)
                    .addComponent(dataDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataDetailPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(viewScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionPaginationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastPaginationButton)
                    .addComponent(nextPaginationButton)
                    .addComponent(paginationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstPaginationButton)
                    .addComponent(previousPaginationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataDetailPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
        );

        pencarianField.setToolTipText("Kotak Pencarian");
        pencarianField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5), javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 16, new java.awt.Color(0, 0, 0)))));
        pencarianField.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pencarianField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Pencarian :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(509, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(pencarianField, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pencarianField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void field_no_ktpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_no_ktpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_no_ktpActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        mdbc.close(stmt);
        mdbc.destroy();
    }//GEN-LAST:event_formWindowClosed
    
    public void updateTable() {
        model.fireTableDataChanged();
    }
    
    private void pencarianFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianFieldActionPerformed
        // TODO add your handling code here:
        String searchText = pencarianField.getText();
        
        // reset where clause
        String sign = "USER SEARCH";
        model.sql.select.removeWhereBySegmentSign(sign);
        
        model.sql.select.whereSegmentStart(sign);
        model.sql.select.where("idSewa", "LIKE", "%" + searchText + "%");
        model.sql.select.orWhere("noKTP", "LIKE", "%" + searchText + "%");
        model.sql.select.whereSegmentEnd(sign);
        
        int newOffset = pagination.isSQLChanged.updatePagination();
        pagination.isSQLChanged.GUIComponent.reinitComboBox();
        pagination.GUIComponent.update();
        
        model.sql.select.offset(newOffset);
        ResultSet rs = model.sql.select.execute();
        model.save(rs);
        
        updateTable();
    }//GEN-LAST:event_pencarianFieldActionPerformed

    private void lastPaginationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastPaginationButtonActionPerformed
        // TODO add your handling code here:
        int newOffset = pagination.jumpToLast();
        pagination.GUIComponent.update();
        
        model.sql.select.offset(newOffset);
        ResultSet rs = model.sql.select.execute();
        model.save(rs);
        
        updateTable();
    }//GEN-LAST:event_lastPaginationButtonActionPerformed

    private void nextPaginationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPaginationButtonActionPerformed
        // TODO add your handling code here:
        int newOffset = pagination.moveNext();
        pagination.GUIComponent.update();
        
        model.sql.select.offset(newOffset);
        ResultSet rs = model.sql.select.execute();
        model.save(rs);
        
        updateTable();
    }//GEN-LAST:event_nextPaginationButtonActionPerformed

    private void paginationComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paginationComboBoxItemStateChanged
        // TODO add your handling code here:
        String _paginationComboBoxStatus = paginationComboBoxStatus.getText();
        
        if (evt.getStateChange() == ItemEvent.DESELECTED &&
            pagination.GUIComponent.getComboBoxStatus() ==
                PaginationPenyewaanGUIComponent.COMBOBOX_ACCEPT_ANY_ACTION)
        {
            System.out.println("Posisi " + "paginationComboBox");
            
            int selectedPage = Integer.valueOf(paginationComboBox
                    .getSelectedItem()
                    .toString());
            
            int newOffset = pagination.jumpTo(selectedPage);
            pagination.GUIComponent.update();
            
            model.sql.select.offset(newOffset);
            ResultSet rs = model.sql.select.execute();
            model.save(rs);
            
            updateTable();
            
        }
    }//GEN-LAST:event_paginationComboBoxItemStateChanged
    
    private void previousPaginationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousPaginationButtonActionPerformed
        // TODO add your handling code here:
        int newOffset = pagination.movePrevious();
        pagination.GUIComponent.update();

        model.sql.select.offset(newOffset); 
        ResultSet rs = model.sql.select.execute();
        model.save(rs);

        updateTable();
    }//GEN-LAST:event_previousPaginationButtonActionPerformed

    private void firstPaginationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPaginationButtonActionPerformed
        // TODO add your handling code here:
        int newOffset = pagination.jumpToFirst();
        pagination.GUIComponent.update();
        
        model.sql.select.offset(newOffset);
        ResultSet rs = model.sql.select.execute();
        model.save(rs);
        
        updateTable();
    }//GEN-LAST:event_firstPaginationButtonActionPerformed

    private void paginationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginationComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_paginationComboBoxActionPerformed

    private void viewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTableMouseClicked
        // TODO add your handling code here:
        ResultSet rs = null;
        int row = viewTable.getSelectedRow();
        if (row != -1) {
            PenyewaanTableModel model = (PenyewaanTableModel) viewTable.getModel();
            
            String noKTP = model.getValueAt(row, 0).toString();
            
            try {
                PreparedStatement pst = null;
                mdbc = new MyDBConnection();
                mdbc.init();
                Connection conn =mdbc.getMyConnection();
                String query = "SELECT noKTP,nama,jenisKelamin,tanggalLahir,pekerjaan,alamat,namaKota,telepon,handphone,email FROM pelanggan INNER JOIN kota on kota.idKota = pelanggan.idKota WHERE noKTP = '"
                        + noKTP + "'";
                pst = conn.prepareStatement(query);
                rs = pst.executeQuery(query);
                rs.next();
                
                int jenkel = Integer.parseInt(rs.getString("jenisKelamin"));
                
                field_no_ktp.setText(rs.getString("noKTP"));
                field_nama.setText(rs.getString("nama"));
                if (jenkel  == 1) {
                    field_jk.setText("Perempuan");
                }else{
                    field_jk.setText("Laki-laki");
                }
                field_tgl_lahir.setText(rs.getString("tanggalLahir"));
                field_pekerjaan.setText(rs.getString("pekerjaan"));
                field_alamat.setText(rs.getString("alamat"));
                field_kota.setText(rs.getString("namaKota"));
                field_telepon.setText(rs.getString("telepon"));
                field_email.setText(rs.getString("email"));
                field_no_hp.setText(rs.getString("handphone"));
                mdbc.close(rs);
            } catch (SQLException e) {
                System.out.println("Error inside `viewTableMouseClicked` : "
                    + e.getMessage());
            }
        }
    }//GEN-LAST:event_viewTableMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened
    public String quotate(String content) {
        return "'" + content + "'";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penyewaanTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penyewaanTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penyewaanTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penyewaanTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penyewaanTable().setVisible(true);
            }
        });
    }
    
    private MyDBConnection mdbc;
    private java.sql.Statement stmt;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dataDetailPanel;
    private javax.swing.JPanel dataDetailPanel2;
    private javax.swing.JTextField dendaPerJamField;
    private javax.swing.JTextField field_alamat;
    private javax.swing.JTextField field_email;
    private javax.swing.JTextField field_jk;
    private javax.swing.JTextField field_kota;
    private javax.swing.JTextField field_nama;
    private javax.swing.JTextField field_no_hp;
    private javax.swing.JTextField field_no_ktp;
    private javax.swing.JTextField field_pekerjaan;
    private javax.swing.JTextField field_telepon;
    private javax.swing.JTextField field_tgl_lahir;
    private javax.swing.JButton firstPaginationButton;
    private javax.swing.JTextField hargaSewa12JamField;
    private javax.swing.JTextField hargaSewa24JamField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton lastPaginationButton;
    private javax.swing.JTextField merkField;
    private javax.swing.JButton nextPaginationButton;
    private javax.swing.JTextField noPolisiField;
    private javax.swing.JComboBox paginationComboBox;
    private javax.swing.JTextField paginationComboBoxStatus;
    private javax.swing.JTextField pencarianField;
    private javax.swing.JLabel positionPaginationLabel;
    private javax.swing.JButton previousPaginationButton;
    private javax.swing.JTextField statusField;
    private javax.swing.JTextField tahunField;
    private javax.swing.JScrollPane viewScrollPane;
    private javax.swing.JTable viewTable;
    private javax.swing.JTextField warnaField;
    // End of variables declaration//GEN-END:variables

}
