/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package belajardatabase.penyewaan;

import belajardatabase.model.KotaTableModel;
import belajardatabase.model.MobilTableModel;
import belajardatabase.model.PelangganTableModel;
import belajardatabase.mysqlop.MyDBConnection;
import belajardatabase.model.PenyewaanTableModel;
import belajardatabase.utilities.Pagination;
import belajardatabase.utilities.PaginationGUIComponent;
import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import java.awt.event.ItemEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.TableColumn;

/**
 *
 * @author ASEP
 */
public class ViewRiwayatSewa extends javax.swing.JPanel {
    PenyewaanTableModel penyewaanModel  = null;
    MobilTableModel     mobilModel      = null;
    PelangganTableModel pelangganModel  = null;
    Pagination          pagination      = null;
    
    KotaTableModel      kotaModel       = null;
    
    /**
     * Creates new form view
     */
    public ViewRiwayatSewa(javax.swing.JFrame frame) {
        initComponents();
        initModel();
        initPagination();
        initTable();
        
        // listen when mainWindow is closed
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                penyewaanModel.sql.closeDBConnection();
                mobilModel.sql.closeDBConnection();
                pelangganModel.sql.closeDBConnection();
            }
        });
    }
    
    public void initModel() {
        ResultSet rs = null;
        
        /* init penyewaan penyewaanModel */
        penyewaanModel = new PenyewaanTableModel();
        
        penyewaanModel.sql.select.where("tanggalKembali", "<>", "0000-00-00");
        penyewaanModel.sql.select.limit(penyewaanModel.dataPerPage);
        penyewaanModel.sql.select.offset(0);
        
        rs = penyewaanModel.sql.select.execute();
        penyewaanModel.save(rs);
        penyewaanModel.sql.getConnection().close(rs);
        
        /* init pelanggan model */
        pelangganModel = new PelangganTableModel();
        /* init mobil model */
        mobilModel = new MobilTableModel();
        /* init kota model */
        kotaModel = new KotaTableModel();
    }
    
    public void initPagination() {
        pagination = new Pagination();
        pagination.setModel(penyewaanModel);
        pagination.setPageLength(penyewaanModel.dataPerPage);
        pagination.GUIComponent.setLabel(positionPaginationLabel);
        pagination.GUIComponent.setComboBox(paginationComboBox);
        pagination.init();
    }
    
     
    public void initTable() {
        viewTable.setModel(penyewaanModel);
        
        // leave only 4 column in table
        for (int i = 4; i < penyewaanModel.getColumnCount(); i++) {
            TableColumn col = viewTable.getColumnModel().getColumn(4);
            viewTable.getColumnModel().removeColumn(col);
        }
        
        updateTable();
    }
          
    private String getPencarianSQLQuery() {
        String cari = pencarianField.getText();
        return "(" +
                    "idSewa like " + quotateWithPercent(cari) + " OR " +
                    "noKTP     like " + quotateWithPercent(cari) +
                ")";
    }
    
    
    public String quotateWithPercent(String content) {
        return "'%" + content + "%'";
    }
    
    public void updateTable() {
        penyewaanModel.fireTableDataChanged();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        firstPaginationButton = new javax.swing.JButton();
        previousPaginationButton = new javax.swing.JButton();
        paginationComboBox = new javax.swing.JComboBox();
        nextPaginationButton = new javax.swing.JButton();
        lastPaginationButton = new javax.swing.JButton();
        positionPaginationLabel = new javax.swing.JLabel();
        viewScrollPane = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        dataDetailPanel2 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        noPolisiField = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        hargaSewa12JamField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        merkField = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        hargaSewa24JamField = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        warnaField = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        dendaPerJamField = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        tahunField = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        statusField = new javax.swing.JTextField();
        dataDetailPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        field_no_ktp = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        field_pekerjaan = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        field_nama = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        field_alamat = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        field_jk = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        field_kota = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        field_tgl_lahir = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        field_telepon = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        field_no_hp = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        field_email = new javax.swing.JTextField();
        pencarianField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(626, 666));
        setMinimumSize(new java.awt.Dimension(626, 666));
        setPreferredSize(new java.awt.Dimension(626, 666));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tabel Penyewaan");

        jPanel1.setMaximumSize(new java.awt.Dimension(626, 666));
        jPanel1.setMinimumSize(new java.awt.Dimension(626, 666));
        jPanel1.setPreferredSize(new java.awt.Dimension(626, 666));

        firstPaginationButton.setText("<<");
        firstPaginationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPaginationButtonActionPerformed(evt);
            }
        });

        previousPaginationButton.setText("<");
        previousPaginationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousPaginationButtonActionPerformed(evt);
            }
        });

        paginationComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paginationComboBoxItemStateChanged(evt);
            }
        });
        paginationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginationComboBoxActionPerformed(evt);
            }
        });

        nextPaginationButton.setText(">");
        nextPaginationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPaginationButtonActionPerformed(evt);
            }
        });

        lastPaginationButton.setText(">>");
        lastPaginationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastPaginationButtonActionPerformed(evt);
            }
        });

        positionPaginationLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        positionPaginationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        positionPaginationLabel.setText("Halaman 1 dari 200");
        positionPaginationLabel.setAlignmentX(0.5F);

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        viewTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        viewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTableMouseClicked(evt);
            }
        });
        viewScrollPane.setViewportView(viewTable);

        dataDetailPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Mobil"));
        dataDetailPanel2.setMaximumSize(new java.awt.Dimension(362, 163));
        dataDetailPanel2.setMinimumSize(new java.awt.Dimension(362, 163));
        dataDetailPanel2.setPreferredSize(new java.awt.Dimension(362, 163));
        dataDetailPanel2.setLayout(new java.awt.GridLayout(4, 2, 40, 10));

        jPanel23.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel28.setText("No. Polisi");
        jPanel23.add(jLabel28);

        noPolisiField.setEditable(false);
        noPolisiField.setText("Pilih baris data");
        jPanel23.add(noPolisiField);

        dataDetailPanel2.add(jPanel23);

        jPanel24.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel29.setText("Harga Sewa 12 Jam");
        jPanel24.add(jLabel29);

        hargaSewa12JamField.setEditable(false);
        hargaSewa12JamField.setText("Pilih baris data");
        jPanel24.add(hargaSewa12JamField);

        dataDetailPanel2.add(jPanel24);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel30.setText("Merk");
        jPanel2.add(jLabel30);

        merkField.setEditable(false);
        merkField.setText("Pilih baris data");
        jPanel2.add(merkField);

        dataDetailPanel2.add(jPanel2);

        jPanel25.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel31.setText("Harga Sewa 24 Jam");
        jPanel25.add(jLabel31);

        hargaSewa24JamField.setEditable(false);
        hargaSewa24JamField.setText("Pilih baris data");
        jPanel25.add(hargaSewa24JamField);

        dataDetailPanel2.add(jPanel25);

        jPanel26.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel32.setText("Warna");
        jPanel26.add(jLabel32);

        warnaField.setEditable(false);
        warnaField.setText("Pilih baris data");
        jPanel26.add(warnaField);

        dataDetailPanel2.add(jPanel26);

        jPanel27.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel33.setText("Denda per Jam");
        jPanel27.add(jLabel33);

        dendaPerJamField.setEditable(false);
        dendaPerJamField.setText("Pilih baris data");
        jPanel27.add(dendaPerJamField);

        dataDetailPanel2.add(jPanel27);

        jPanel28.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel34.setText("Tahun");
        jPanel28.add(jLabel34);

        tahunField.setEditable(false);
        tahunField.setText("Pilih baris data");
        jPanel28.add(tahunField);

        dataDetailPanel2.add(jPanel28);

        jPanel29.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel35.setText("Status");
        jPanel29.add(jLabel35);

        statusField.setEditable(false);
        statusField.setText("Pilih baris data");
        jPanel29.add(statusField);

        dataDetailPanel2.add(jPanel29);

        dataDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Pelanggan"));
        dataDetailPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dataDetailPanel.setMinimumSize(new java.awt.Dimension(367, 163));
        dataDetailPanel.setLayout(new java.awt.GridLayout(5, 5, 30, 10));

        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel8.setText("No. KTP");
        jPanel4.add(jLabel8);

        field_no_ktp.setEditable(false);
        field_no_ktp.setText("Pilih baris data");
        field_no_ktp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_no_ktpActionPerformed(evt);
            }
        });
        jPanel4.add(field_no_ktp);

        dataDetailPanel.add(jPanel4);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel9.setText("Pekerjaan");
        jPanel3.add(jLabel9);

        field_pekerjaan.setEditable(false);
        field_pekerjaan.setText("Pilih baris data");
        jPanel3.add(field_pekerjaan);

        dataDetailPanel.add(jPanel3);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel10.setText("Nama");
        jPanel5.add(jLabel10);

        field_nama.setEditable(false);
        field_nama.setText("Pilih baris data");
        jPanel5.add(field_nama);

        dataDetailPanel.add(jPanel5);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel11.setText("Alamat");
        jPanel11.add(jLabel11);

        field_alamat.setEditable(false);
        field_alamat.setText("Pilih baris data");
        jPanel11.add(field_alamat);

        dataDetailPanel.add(jPanel11);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel12.setText("Jenis Kelamin");
        jPanel8.add(jLabel12);

        field_jk.setEditable(false);
        field_jk.setText("Pilih baris data");
        jPanel8.add(field_jk);

        dataDetailPanel.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel13.setText("Kota");
        jPanel9.add(jLabel13);

        field_kota.setEditable(false);
        field_kota.setText("Pilih baris data");
        jPanel9.add(field_kota);

        dataDetailPanel.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel14.setText("Tanggal Lahir");
        jPanel10.add(jLabel14);

        field_tgl_lahir.setEditable(false);
        field_tgl_lahir.setText("Pilih baris data");
        jPanel10.add(field_tgl_lahir);

        dataDetailPanel.add(jPanel10);

        jPanel12.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel15.setText("Telepon");
        jPanel12.add(jLabel15);

        field_telepon.setEditable(false);
        field_telepon.setText("Pilih baris data");
        jPanel12.add(field_telepon);

        dataDetailPanel.add(jPanel12);

        jPanel13.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel16.setText("No. HP");
        jPanel13.add(jLabel16);

        field_no_hp.setEditable(false);
        field_no_hp.setText("Pilih baris data");
        jPanel13.add(field_no_hp);

        dataDetailPanel.add(jPanel13);

        jPanel14.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel17.setText("Email");
        jPanel14.add(jLabel17);

        field_email.setEditable(false);
        field_email.setText("Pilih baris data");
        jPanel14.add(field_email);

        dataDetailPanel.add(jPanel14);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                    .addComponent(dataDetailPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dataDetailPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewScrollPane)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstPaginationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previousPaginationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paginationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextPaginationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastPaginationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(positionPaginationLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(viewScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionPaginationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastPaginationButton)
                    .addComponent(nextPaginationButton)
                    .addComponent(paginationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstPaginationButton)
                    .addComponent(previousPaginationButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pencarianField.setToolTipText("Kotak Pencarian");
        pencarianField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5), javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 16, new java.awt.Color(0, 0, 0)))));
        pencarianField.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pencarianField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Pencarian :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pencarianField, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pencarianField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstPaginationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPaginationButtonActionPerformed
        // TODO add your handling code here:
        int newOffset = pagination.jumpToFirst();
        pagination.GUIComponent.update();

        penyewaanModel.sql.select.offset(newOffset);
        ResultSet rs = penyewaanModel.sql.select.execute();
        penyewaanModel.save(rs);
        penyewaanModel.sql.getConnection().close(rs);

        updateTable();
    }//GEN-LAST:event_firstPaginationButtonActionPerformed

    private void previousPaginationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousPaginationButtonActionPerformed
        // TODO add your handling code here:
        int newOffset = pagination.movePrevious();
        pagination.GUIComponent.update();

        penyewaanModel.sql.select.offset(newOffset);
        ResultSet rs = penyewaanModel.sql.select.execute();
        penyewaanModel.save(rs);
        penyewaanModel.sql.getConnection().close(rs);

        updateTable();
    }//GEN-LAST:event_previousPaginationButtonActionPerformed

    private void paginationComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paginationComboBoxItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == ItemEvent.DESELECTED &&
            pagination.GUIComponent.getComboBoxStatus() ==
            PaginationGUIComponent.COMBOBOX_ACCEPT_ANY_ACTION)
        {
            System.out.println("Posisi " + "paginationComboBox");

            int selectedPage = Integer.valueOf(paginationComboBox
                .getSelectedItem()
                .toString());

            int newOffset = pagination.jumpTo(selectedPage);
            pagination.GUIComponent.update();

            penyewaanModel.sql.select.offset(newOffset);
            ResultSet rs = penyewaanModel.sql.select.execute();
            penyewaanModel.save(rs);
            penyewaanModel.sql.getConnection().close(rs);

            updateTable();

        }
    }//GEN-LAST:event_paginationComboBoxItemStateChanged

    private void paginationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginationComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_paginationComboBoxActionPerformed

    private void nextPaginationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPaginationButtonActionPerformed
        // TODO add your handling code here:
        int newOffset = pagination.moveNext();
        pagination.GUIComponent.update();

        penyewaanModel.sql.select.offset(newOffset);
        ResultSet rs = penyewaanModel.sql.select.execute();
        penyewaanModel.save(rs);
        penyewaanModel.sql.getConnection().close(rs);

        updateTable();
    }//GEN-LAST:event_nextPaginationButtonActionPerformed

    private void lastPaginationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastPaginationButtonActionPerformed
        // TODO add your handling code here:
        int newOffset = pagination.jumpToLast();
        pagination.GUIComponent.update();

        penyewaanModel.sql.select.offset(newOffset);
        ResultSet rs = penyewaanModel.sql.select.execute();
        penyewaanModel.save(rs);
        penyewaanModel.sql.getConnection().close(rs);

        updateTable();
    }//GEN-LAST:event_lastPaginationButtonActionPerformed

    /**
     * Fill in data detail pelanggan from specific pelanggan
     */
    private void showDataDetailOfPelanggan(int selectedRow) {
        String noKTP = "";
        String nama = "";
        String tanggalLahir = "";
        String pekerjaan = "";
        String alamat = "";
        String jenisKelamin = "";
        int idKota = 0;
        String telepon = "";
        String handphone = "";
        String email = "";
        
        int row = selectedRow;
        noKTP = viewTable.getValueAt(row, 2).toString();
        
        pelangganModel.sql.select.reset();
        pelangganModel.sql.select.where("noKTP", "=", noKTP);
        ResultSet rs = pelangganModel.sql.select.execute();
        try {
            if (rs.next() == false) return;
           
            nama = rs.getString("nama");
            tanggalLahir = rs.getString("tanggalLahir");
            pekerjaan = rs.getString("pekerjaan");
            alamat = rs.getString("alamat");
            jenisKelamin = rs.getString("jenisKelamin");
            idKota = rs.getInt("idKota");
            telepon = rs.getString("telepon");
            handphone = rs.getString("handphone");
            email = rs.getString("email");
        } catch (SQLException e) {
            
        }
        mobilModel.sql.getConnection().close(rs);
        
        /* get nama kota from id kota */
        String namaKota = kotaModel.getNamaKotaById(idKota);
        /* get jenis kelamin */
        int jenkel = Integer.parseInt(jenisKelamin);

        field_no_ktp.setText(noKTP);
        field_nama.setText(nama);
        if (jenkel == PelangganTableModel.PEREMPUAN) {
            field_jk.setText("Perempuan");
        }else{
            field_jk.setText("Laki-laki");
        }
        field_tgl_lahir.setText(tanggalLahir);
        field_pekerjaan.setText(pekerjaan);
        field_alamat.setText(alamat);
        field_kota.setText(namaKota);
        field_telepon.setText(telepon);
        field_email.setText(email);
        field_no_hp.setText(handphone);
    }
    
    /**
     * Fill in data detail pelanggan from specific pelanggan
     */
    private void showDataDetailOfMobil(int selectedRow) {
        String noPolisi = "";
        String merk = "";
        String warna = "";
        String tahun = "";
        String hargaSewa12Jam = "";
        String hargaSewa24Jam = "";
        String dendaPerJam = "";
        String status = "";
        
        int row = selectedRow;
        noPolisi = viewTable.getValueAt(row, 1).toString();
        
        mobilModel.sql.select.reset();
        mobilModel.sql.select.where("noPolisi", "=", noPolisi);
        ResultSet rs = mobilModel.sql.select.execute();
        try {
            if (rs.next() == false) return;
            
            merk = rs.getString("merk");
            warna = rs.getString("warna");
            tahun = rs.getString("tahun");
            hargaSewa12Jam = rs.getString("hargaSewa12Jam");
            hargaSewa24Jam = rs.getString("hargaSewa24Jam");
            dendaPerJam = rs.getString("dendaPerJam");
            status = rs.getString("status");
        } catch (SQLException e) {
            
        }
        mobilModel.sql.getConnection().close(rs);
        
        noPolisiField.setText(noPolisi);
        merkField.setText(merk);
        warnaField.setText(warna);
        tahunField.setText(tahun);
        hargaSewa12JamField.setText(hargaSewa12Jam);
        hargaSewa24JamField.setText(hargaSewa24Jam);
        dendaPerJamField.setText(dendaPerJam);
        statusField.setText(
            Integer.valueOf(status) == MobilTableModel.STATUS_TERSEDIA
            ? "Tersedia" : "Tidak Tersedia"
        );
    }
    
    private void viewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTableMouseClicked
        int row = viewTable.getSelectedRow();
        if (row != -1) {
            showDataDetailOfPelanggan(row);
            showDataDetailOfMobil(row);
        }
    }//GEN-LAST:event_viewTableMouseClicked

    private void field_no_ktpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_no_ktpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_no_ktpActionPerformed

    private void pencarianFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianFieldActionPerformed
        // TODO add your handling code here:
        String searchText = pencarianField.getText();

        // reset where clause
        String sign = "USER SEARCH";
        penyewaanModel.sql.select.removeWhereBySegmentSign(sign);

        penyewaanModel.sql.select.whereSegmentStart(sign);
        penyewaanModel.sql.select.where("idSewa", "LIKE", "%" + searchText + "%");
        penyewaanModel.sql.select.orWhere("noKTP", "LIKE", "%" + searchText + "%");
        penyewaanModel.sql.select.whereSegmentEnd(sign);

        int newOffset = pagination.isSQLChanged.updatePagination();
        pagination.isSQLChanged.GUIComponent.reinitComboBox();
        pagination.GUIComponent.update();

        penyewaanModel.sql.select.offset(newOffset);
        ResultSet rs = penyewaanModel.sql.select.execute();
        penyewaanModel.save(rs);
        penyewaanModel.sql.getConnection().close(rs);

        updateTable();
    }//GEN-LAST:event_pencarianFieldActionPerformed

    public String quotate(String content) {
        return "'" + content + "'";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dataDetailPanel;
    private javax.swing.JPanel dataDetailPanel2;
    private javax.swing.JTextField dendaPerJamField;
    private javax.swing.JTextField field_alamat;
    private javax.swing.JTextField field_email;
    private javax.swing.JTextField field_jk;
    private javax.swing.JTextField field_kota;
    private javax.swing.JTextField field_nama;
    private javax.swing.JTextField field_no_hp;
    private javax.swing.JTextField field_no_ktp;
    private javax.swing.JTextField field_pekerjaan;
    private javax.swing.JTextField field_telepon;
    private javax.swing.JTextField field_tgl_lahir;
    private javax.swing.JButton firstPaginationButton;
    private javax.swing.JTextField hargaSewa12JamField;
    private javax.swing.JTextField hargaSewa24JamField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lastPaginationButton;
    private javax.swing.JTextField merkField;
    private javax.swing.JButton nextPaginationButton;
    private javax.swing.JTextField noPolisiField;
    private javax.swing.JComboBox paginationComboBox;
    private javax.swing.JTextField pencarianField;
    private javax.swing.JLabel positionPaginationLabel;
    private javax.swing.JButton previousPaginationButton;
    private javax.swing.JTextField statusField;
    private javax.swing.JTextField tahunField;
    private javax.swing.JScrollPane viewScrollPane;
    private javax.swing.JTable viewTable;
    private javax.swing.JTextField warnaField;
    // End of variables declaration//GEN-END:variables
}
